"""
AI chat router — POST /api/v1/ai/chat with Server-Sent Events streaming.

Request body:
  {
    "messages": [{"role": "user"|"assistant", "content": "..."}],
    "thread_id": "<uuid>"   # optional — generated by frontend, persisted in localStorage
  }

Response: text/event-stream
  data: {"type": "session",  "thread_id": "..."}     — first event, confirms thread_id
  data: {"type": "token",    "content": "..."}        — incremental LLM text
  data: {"type": "tool_call","name": "...","result": "..."} — tool executed
  data: {"type": "done"}                              — stream end

Memory strategy:
  If the PostgresSaver checkpointer is available (production), the agent
  stores conversation state in PostgreSQL keyed by thread_id. The frontend
  only needs to send the NEW user message — the agent recovers full history
  from the checkpoint.

  If checkpointer is None (test / stateless fallback), all messages are sent
  on every request (previous behaviour, no DB required).
"""

import json
import uuid
import logging

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from langchain_core.messages import HumanMessage

from app.core.dependencies import CurrentUser, DB
from app.ai.agent import build_agent
from app.ai.checkpoint import get_checkpointer

router = APIRouter(prefix="/ai", tags=["AI Agent"])


class ChatMessage(BaseModel):
    role: str   # "user" | "assistant"
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    thread_id: str | None = None  # UUID generated and persisted by the frontend
    current_ticket_id: str | None = None  # The ID of the ticket the user is currently viewing
    selected_ticket_ids: list[str] | None = None  # List of tickets selected in the UI


@router.get("/history/{thread_id}")
async def get_chat_history(thread_id: str):
    """
    Fetch the historical messages for a specific thread from the checkpointer.
    This allows the frontend to restore the UI state after a refresh.
    """
    checkpointer = get_checkpointer()
    if not checkpointer:
        return {"messages": []}

    config = {"configurable": {"thread_id": thread_id}}
    state = await checkpointer.aget(config)
    
    if not state or "messages" not in state.values:
        return {"messages": []}

    # Convert LangChain messages to our ChatMessage schema
    history = []
    for msg in state.values["messages"]:
        role = "user" if msg.type == "human" else "assistant"
        # Skip tool messages in the basic UI history to keep it clean
        if msg.type in ["human", "ai"]:
            history.append({"role": role, "content": msg.content})
            
    return {"messages": history}


@router.post("/chat")
async def chat(
    request: ChatRequest,
    db: DB,
    current_user: CurrentUser,
):
    checkpointer = get_checkpointer()
    # Fallback to current_user.id if no thread_id is provided.
    thread_id = request.thread_id or str(current_user.id)
    
    v_logger = logging.getLogger("uvicorn.error")
    v_logger.info("AI Session: thread_id=%s (Source: %s)", thread_id, "Frontend" if request.thread_id else "UserFallback")

    # 3. Build dynamic context (Ticket Awareness)
    context_parts = []
    
    # 3a. Current Ticket Context
    if request.current_ticket_id:
        try:
            from app.services.ticket_service import get_ticket
            ticket_id_uuid = uuid.UUID(request.current_ticket_id)
            ticket_data = await get_ticket(db, ticket_id_uuid)
            if ticket_data:
                context_parts.append(
                    f"USER IS CURRENTLY VIEWING THIS TICKET (USE THIS FULL ID FOR ACTIONS):\n"
                    f"FULL_ID: {str(ticket_data.id)}\n"
                    f"Title: {ticket_data.title}\n"
                    f"Status: {ticket_data.status.value}\n"
                    f"Priority: {ticket_data.priority.value}\n"
                    f"Description: {ticket_data.description or 'No description'}"
                )
        except Exception as e:
            v_logger.warning("AI Context: Failed to fetch current ticket details: %s", str(e))

    # 3b. Selected Tickets Context
    if request.selected_ticket_ids and len(request.selected_ticket_ids) > 0:
        try:
            from app.models.ticket import Ticket
            from sqlalchemy import select
            # Only fetch if they aren't already the current ticket (avoid duplicates)
            other_ids = [uuid.UUID(tid) for tid in request.selected_ticket_ids if tid != request.current_ticket_id]
            if other_ids:
                res = await db.execute(select(Ticket).where(Ticket.id.in_(other_ids)))
                selected_tickets = res.scalars().all()
                if selected_tickets:
                    selection_text = "USER HAS SELECTED THESE TICKETS (USE THESE FULL IDs FOR ACTIONS):\n"
                    for t in selected_tickets:
                        selection_text += f"- Title: {t.title} | Status: {t.status.value} | FULL_ID: {str(t.id)}\n"
                    context_parts.append(selection_text)
        except Exception as e:
            v_logger.warning("AI Context: Failed to fetch selected tickets: %s", str(e))

    extra_context = ""
    if context_parts:
        extra_context = "\n\n" + "\n\n---\n\n".join(context_parts)
        v_logger.info("AI Context: Injected details for current/selected tickets")

    try:
        agent = build_agent(db, current_user, system_context=extra_context)
    except Exception as e:
        error_msg = str(e)
        v_logger.error("AI Initialization Failed: %s", error_msg, exc_info=True)
        async def error_generator():
            yield f"data: {json.dumps({'type': 'error', 'content': f'*(Error de Configuración: {error_msg})*'})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"
        return StreamingResponse(error_generator(), media_type="text/event-stream")

    if checkpointer and thread_id:
        v_logger.info("Memory: Loading persistent history for thread %s", thread_id)
        # Persistent mode: send only the new user message; agent recovers history
        initial_state = {
            "messages": [HumanMessage(content=request.messages[-1].content)],
            "remaining_steps": 40,
        }
    else:
        v_logger.warning("Memory: Running in STATELESS mode (no checkpointer or no thread_id)")
        # Stateless fallback: send the full conversation history
        initial_state = {
            "messages": [
                {"role": msg.role, "content": msg.content}
                for msg in request.messages
            ],
            "remaining_steps": 40,
        }

    config = {"configurable": {"thread_id": thread_id}}
    
    # DEBUG: Check what's currently in memory
    if checkpointer:
        state = await agent.aget_state(config)
        history_count = len(state.values.get("messages", [])) if state.values else 0
        v_logger.info("Memory Check: Thread %s has %d messages in DB", thread_id, history_count)

    async def event_stream():
        # First event: confirm the thread_id so the frontend can persist it
        yield f"data: {json.dumps({'type': 'session', 'thread_id': thread_id})}\n\n"
        
        # Immediate visual feedback: send a subtle "thinking" token to break buffering
        yield f"data: {json.dumps({'type': 'token', 'content': ' '})}\n\n"

        try:
            has_content = False
            active_model = "IA"
            async for event in agent.astream_events(
                initial_state,
                version="v2",
                config=config
            ):
                kind = event["event"]
                
                # Identify which model is responding
                if kind == "on_chat_model_start":
                    m_name = event.get("name", "")
                    if "Google" in m_name: active_model = "Gemini"
                    elif "OpenAI" in m_name: active_model = "GPT"
                    v_logger.info("AI Model Starting: %s (%s)", m_name, active_model)

                if kind == "on_chat_model_stream":
                    chunk = event["data"]["chunk"]
                    if chunk and hasattr(chunk, "content") and chunk.content:
                        has_content = True
                        content = chunk.content
                        # Prepend debug info only on the very first token
                        if not hasattr(event_stream, "_debug_sent"):
                            content = f"*(Modo: {active_model})* " + content
                            setattr(event_stream, "_debug_sent", True)
                            
                        yield f"data: {json.dumps({'type': 'token', 'content': content})}\n\n"

                elif kind == "on_tool_start":
                    tool_name = event.get("name", "")
                    payload = json.dumps({
                        "type": "tool_start",
                        "name": tool_name,
                    })
                    yield f"data: {payload}\n\n"

                elif kind == "on_tool_end":
                    tool_name = event.get("name", "")
                    tool_output = event.get("data", {}).get("output", "")
                    payload = json.dumps({
                        "type": "tool_call",
                        "name": tool_name,
                        "result": str(tool_output),
                    })
                    yield f"data: {payload}\n\n"

            if not has_content:
                v_logger.warning("AI Stream finished with NO content. Sending safety message.")
                yield f"data: {json.dumps({'type': 'token', 'content': '*(Sistema: Los modelos de IA no han respondido. Por favor, intenta de nuevo.)*'})}\n\n"

            yield f"data: {json.dumps({'type': 'done'})}\n\n"

        except Exception as e:
            error_msg = str(e)
            v_logger.error("Streaming error in chat: %s", error_msg, exc_info=True)
            
            # User-friendly explanation for Quota/API issues
            friendly_msg = error_msg
            if "429" in error_msg or "quota" in error_msg.lower():
                friendly_msg = "*(Sistema: Se ha alcanzado el límite de uso de la IA gratuita. Por favor, espera unos segundos o contacta con el administrador para activar el modo de respaldo.)*"
            elif "api_key" in error_msg.lower() or "401" in error_msg:
                friendly_msg = "*(Sistema: Error de configuración en la clave de la IA. Por favor, revisa las variables de entorno.)*"
            
            yield f"data: {json.dumps({'type': 'error', 'content': friendly_msg})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
