"""
AI chat router — POST /api/v1/ai/chat with Server-Sent Events streaming.

Request body:
  {
    "messages": [{"role": "user"|"assistant", "content": "..."}],
    "thread_id": "<uuid>"   # optional — generated by frontend, persisted in localStorage
  }

Response: text/event-stream
  data: {"type": "session",  "thread_id": "..."}     — first event, confirms thread_id
  data: {"type": "token",    "content": "..."}        — incremental LLM text
  data: {"type": "tool_call","name": "...","result": "..."} — tool executed
  data: {"type": "done"}                              — stream end

Memory strategy:
  If the PostgresSaver checkpointer is available (production), the agent
  stores conversation state in PostgreSQL keyed by thread_id. The frontend
  only needs to send the NEW user message — the agent recovers full history
  from the checkpoint.

  If checkpointer is None (test / stateless fallback), all messages are sent
  on every request (previous behaviour, no DB required).
"""

import json
import uuid

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.core.dependencies import CurrentUser, DB
from app.ai.agent import build_agent
from app.ai.checkpoint import get_checkpointer

router = APIRouter(prefix="/ai", tags=["AI Agent"])


class ChatMessage(BaseModel):
    role: str   # "user" | "assistant"
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    thread_id: str | None = None  # UUID generated and persisted by the frontend


@router.post("/chat")
async def chat(
    request: ChatRequest,
    db: DB,
    current_user: CurrentUser,
):
    """
    Stream an AI response. Supports persistent memory via thread_id.

    With checkpointer (production):
      - thread_id identifies the conversation in PostgreSQL.
      - Only the latest user message is passed; the agent loads history
        from the checkpoint automatically.

    Without checkpointer (stateless fallback):
      - Full message history is passed on every request (legacy behavior).
    """
    checkpointer = get_checkpointer()
    thread_id = request.thread_id or str(uuid.uuid4())
    agent = build_agent(db, current_user)

    if checkpointer and request.thread_id:
        # Persistent mode: send only the new user message; agent recovers history
        lc_messages = [{"role": "user", "content": request.messages[-1].content}]
    else:
        # Stateless fallback: send the full conversation history
        lc_messages = [
            {"role": msg.role, "content": msg.content}
            for msg in request.messages
        ]

    config = {"configurable": {"thread_id": thread_id}}

    async def event_stream():
        # First event: confirm the thread_id so the frontend can persist it
        yield f"data: {json.dumps({'type': 'session', 'thread_id': thread_id})}\n\n"

        try:
            async for event in agent.astream_events(
                {"messages": lc_messages},
                config=config,
                version="v2",
            ):
                kind = event.get("event")

                if kind == "on_chat_model_stream":
                    chunk = event.get("data", {}).get("chunk")
                    if chunk and hasattr(chunk, "content") and chunk.content:
                        payload = json.dumps({"type": "token", "content": chunk.content})
                        yield f"data: {payload}\n\n"

                elif kind == "on_tool_end":
                    tool_name = event.get("name", "")
                    tool_output = event.get("data", {}).get("output", "")
                    payload = json.dumps({
                        "type": "tool_call",
                        "name": tool_name,
                        "result": str(tool_output),
                    })
                    yield f"data: {payload}\n\n"

            yield f"data: {json.dumps({'type': 'done'})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'content': str(e)})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
